// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package store

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64          `json:"id"`
	Avatar    sql.NullString `json:"avatar"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Phone     sql.NullString `json:"phone"`
	CreatedAt time.Time      `json:"created_at"`
}
