definitions:
  auth.EmailVerificationRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  auth.LoginRequest:
    properties:
      email:
        description: Required. User email
        type: string
      password:
        description: Required. User password. Min 8 characters, max 100 characters
        maxLength: 100
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginResponse:
    properties:
      token:
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      email:
        description: Required. User email
        type: string
      otp:
        description: Required. OTP. min 111111, max 999999
        maximum: 999999
        minimum: 111111
        type: integer
      password:
        description: Required. User password. Min 8 characters, max 100 characters
        maxLength: 100
        minLength: 8
        type: string
      username:
        description: Required. User name. Max length=100, min length 1
        maxLength: 100
        minLength: 1
        type: string
    required:
    - email
    - otp
    - password
    - username
    type: object
  auth.RegisterResponse:
    properties:
      token:
        type: string
    type: object
  auth.ResetPasswordRequest:
    properties:
      email:
        description: Required. User email
        type: string
      otp:
        description: Required. OTP. min 111111, max 999999
        maximum: 999999
        minimum: 111111
        type: integer
      password:
        description: Required. User password. Min 8 characters, max 100 characters
        maxLength: 100
        minLength: 8
        type: string
    required:
    - email
    - otp
    - password
    type: object
  users.OnboardingRequest:
    properties:
      birthDate:
        type: string
      gender:
        enum:
        - male
        - female
        - other
        type: string
      location:
        properties:
          latitude:
            type: number
          longitude:
            type: number
        required:
        - latitude
        - longitude
        type: object
      name:
        description: User name
        maxLength: 100
        minLength: 1
        type: string
    required:
    - birthDate
    - gender
    - location
    - name
    type: object
  users.UserDetailsResponse:
    properties:
      avatar:
        type: string
      birthDate:
        type: string
      gender:
        type: string
      lastLogin:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
      userID:
        type: integer
      username:
        type: string
    type: object
  utils.Response:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/email_verification:
    post:
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.EmailVerificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Sends verification email.
      tags:
      - auth
  /auth/login:
    post:
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      summary: API for user login.
      tags:
      - auth
  /auth/register:
    post:
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth.RegisterResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      summary: API for new user registration.
      tags:
      - auth
  /auth/reset:
    post:
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Resets user password.
      tags:
      - auth
  /users/details:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                data:
                  $ref: '#/definitions/users.UserDetailsResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - ApiKeyAuth: []
      summary: Get user details
      tags:
      - users
  /users/onboarding:
    post:
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/users.OnboardingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - ApiKeyAuth: []
      summary: Api thats create basic onboarding details for a user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
